sudo: false
language: node_js
node_js:
  - "6"
cache:
  directories:
  - node_modules
# setup all commands ourselves for clarity
install:
  - npm install
# skip default test step completely
# (using job stages below)
# there will be dummy "test" job though
script: echo "Skip default single test script"
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: info
      script: echo "Testing node $(node -v)"
    - stage: info
      script: echo "info message 2"
    - stage: message
      script: echo "Message 1"
    - stage: message
      script: echo "Message 2"
