language: node_js
node_js:
  - "6"

# setup all commands ourselves for clarity
install:
  - npm install
# skip default test step completely
# (using job stages below)
# there will be dummy "test" job though
jobs:
  include:
    - stage: info
      script: echo "Testing node $(node -v)"
    - stage: message
      script: echo "This is a test message"
