language: node_js
node_js:
  - "6"

# setup all commands ourselves for clarity
install:
  - npm install
jobs:
  include:
    - stage: info
      script: echo "Testing node $(node -v)"
    - stage: test
      script: npm test
